name: CI/CD Portafolio App
description: Deploy de la aplicación Portafolio a Kubernetes con validaciones y notificaciones
# Este workflow se encarga de desplegar la aplicación Portafolio a un clúster de Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    # Evita que el job corra si fue ejecutado por el bot
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    ###
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      # Configurar Git
      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      ####
      # Detectar cambios en carpeta app/
      - name: Detectar cambios en carpeta app/
        id: check_app
        run: |
          git fetch --depth=2 origin ${{ github.ref }}
          if git diff --quiet HEAD^ HEAD -- ${{ github.workspace }}/apps/portafolio/app; then
            echo "Sin cambios en carpeta app/"
            echo "app_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Cambios detectados en carpeta app/"
            echo "app_changed=true" >> $GITHUB_OUTPUT
          fi

      ###############################################
      # Instalacion de herramientas necesarias para K8s
      # Instalar Age y SOPS
      # - name: Instalar Age y SOPS
      #   run: |
      #     curl -L https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz | tar xz
      #     sudo mv age/age /usr/local/bin/
      #     sudo mv age/age-keygen /usr/local/bin/

      #     curl -L https://github.com/mozilla/sops/releases/download/v3.8.1/sops-v3.8.1.linux -o /usr/local/bin/sops
      #     chmod +x /usr/local/bin/sops
      # # Configurar clave privada de Age
      # - name: Configurar clave privada de Age
      #   run: |
      #     mkdir -p ~/.config/sops/age
      #     echo "${{ secrets.SOPS_AGE_KEY }}" > ~/.config/sops/age/keys.txt

      # ###############################
      # # Linting con Kube-linter
      # - name: Linting con kube-linter
      #   run: |
      #     set -euo pipefail

      #     # Descargar y extraer kube-linter
      #     curl -sSL https://github.com/stackrox/kube-linter/releases/latest/download/kube-linter-linux.tar.gz | tar xz

      #     echo "🔍 Ejecutando kube-linter sobre los manifiestos de Kustomize..."

      #     # Ejecutar kube-linter y capturar errores
      #     if ! ./kube-linter lint <(kustomize build --enable-alpha-plugins --enable-exec ${{ github.workspace }}/apps/portafolio/k8s/overlays/prod); then
      #       echo "❌ KubeLinter encontró errores. Por favor corrige antes de continuar."
      #       exit 1
      #     else
      #       echo "✅ KubeLinter: sin errores."
      #     fi
      # # Validación con Kubeconform (reemplazo moderno de kubeval)
      # - name: Validación de manifiestos con kubeconform
      #   run: |
      #     set -euo pipefail

      #     echo "📥 Descargando kubeconform..."
      #     curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz

      #     echo "🔍 Ejecutando kubeconform sobre los manifiestos generados por Kustomize..."

      #     if ! kustomize build --enable-alpha-plugins --enable-exec ${{ github.workspace }}/apps/portafolio/k8s/overlays/prod | ./kubeconform -strict -summary -kubernetes-version 1.32.4 -skip "IngressRoute"  --ignore-missing-schemas ; then
      #       echo "❌ kubeconform detectó errores de validación en los manifiestos. Corrígelos antes de hacer deploy."
      #       exit 1
      #     else
      #       echo "✅ kubeconform: todos los manifiestos son válidos y cumplen con los esquemas de Kubernetes."
      #     fi
