services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app:latest
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
            - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
        environment:
            - DB_HOST=mariadb
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
            - REDIS_HOST=redis
            - REDIS_PASSWORD=my_redis_secret
        depends_on:
            - mariadb
            - redis
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./storage:/var/www/storage
        depends_on:
            - app
        networks:
            - laravel

    mariadb:
        image: mariadb:11.3
        container_name: mariadb
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=secret
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:7-alpine
        container_name: redis
        restart: unless-stopped
        command: ["redis-server", "--requirepass", "my_redis_secret"]
        volumes:
            - redis_data:/data
        environment:
            - REDIS_PASSWORD=my_redis_secret
        networks:
            - laravel

volumes:
    mariadb_data:
    redis_data:

networks:
    laravel:
        driver: bridge
