# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - middlewares/rate-limit.yaml
  - middlewares/secure-headers.yaml
  - laravel-config-env.yaml
  - nginx-config.yaml
  - pvc-laravel.yaml
  - laravel-deploy.yaml
  - service.yaml
  - ingressroute.yaml
  - hpa.yaml
  - job/laravel-init.yaml

generators:
  - secrets/ksops-generator.yaml

images:
  - name: migbertweb/laravel-prueba
    newName: migbertweb/laravel-prueba
    newTag: latest-arm64
