apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: portafolio
  labels:
    app: laravel-app
    version: v1
  annotations:
    ignore-check.kube-linter.io/privileged-container: "This deployment needs to run as privileged"
    ignore-check.kube-linter.io/no-read-only-root-fs: "This deployment needs to run as privileged"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      initContainers:
        - name: generate-assets
          image: migbertweb/laravel-prueba
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "🔧 Verificando assets de Vite..."
              if [ ! -f "/var/www/public/build/manifest.json" ]; then
                echo "⚠️ manifest.json no encontrado, generando assets..."
                cd /var/www
                npm install
                npm run build
                echo "✅ Assets generados"
              else
                echo "✅ Assets ya existen"
              fi
          volumeMounts:
            - name: public-assets
              mountPath: /var/www/public
        - name: copy-public-assets
          image: migbertweb/laravel-prueba
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "📁 Copiando assets públicos..."
              cp -r /var/www/public/* /public-assets/ 2>/dev/null || true
              echo "📋 Contenido del directorio public-assets:"
              ls -la /public-assets/
              if [ -d "/public-assets/build" ]; then
                echo "✅ Directorio build copiado correctamente"
                ls -la /public-assets/build/
              else
                echo "❌ Error: Directorio build no se copió"
              fi
          volumeMounts:
            - name: public-assets
              mountPath: /public-assets
      containers:
        - name: laravel-app
          image: migbertweb/laravel-prueba
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 9000
              name: php-fpm
          envFrom:
            - configMapRef:
                name: laravel-config-env
            - secretRef:
                name: laravel-secret-env
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/storage
              subPath: ""
            - name: laravel-tmp
              mountPath: /tmp
            - name: public-assets
              mountPath: /var/www/public
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - SETGID
                - SETUID
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/storage
              subPath: ""
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /run
            - name: nginx-tmp
              mountPath: /tmp
            - name: public-assets
              mountPath: /var/www/public
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: laravel-storage-pvc
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
        - name: laravel-tmp
          emptyDir: {}
        - name: public-assets
          emptyDir: {}
