apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: portafolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-app
          image: migbertweb/portafolio-app
          securityContext:
            runAsNonRoot: false
            runAsUser: 101
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: laravel-config-env
            - secretRef:
                name: laravel-secret-env
          volumeMounts:
            - name: laravel-code
              mountPath: /var/www
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: laravel-code
          emptyDir: {}
          # Uncomment the following lines if you want to use a PersistentVolumeClaim
          # - name: laravel-code
          #   persistentVolumeClaim:
          #     claimName: laravel-pvc
