apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config-env
  namespace: portafolio
data:
  APP_NAME: Migbertweb
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: http://localhost
  #
  LOG_CHANNEL: stack
  LOG_LEVEL: info

  DB_CONNECTION: mysql
  DB_HOST: mariadb-service.mysql-ns.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: laravel_db
  DB_CHARSET: utf8mb4
  DB_COLLATION: utf8mb4_unicode_ci

  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_USERNAME: ""
  REDIS_DB: "0"
  REDIS_CACHE_DB: "1"
  CACHE_DRIVER: redis
  SESSION_DRIVER: redis
  QUEUE_CONNECTION: redis

  # Configuración de cache y session
  CACHE_STORE: redis
  SESSION_STORE: redis

  # Configuración de vistas
  VIEW_COMPILED_PATH: /var/www/storage/framework/views
