apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: portafolio
  labels:
    app: laravel-nginx
data:
  default.conf: |
    # Configuración de upstream para PHP-FPM
    upstream php-fpm {
        server localhost:9000;
        keepalive 32;
    }

    # Configuración principal del servidor
    server {
        listen 80;
        server_name _;
        
        # Configuración de seguridad mejorada
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://test.migbertweb.xyz; style-src 'self' 'unsafe-inline' https://fonts.bunny.net https://test.migbertweb.xyz; font-src 'self' https://fonts.bunny.net; img-src 'self' data: https:; connect-src 'self' https://test.migbertweb.xyz; worker-src 'self' blob:;" always;
        
        # Configuración de logs
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log warn;
        
        # Document root
        root /var/www/public;
        index index.php index.html;
        
        # Configuración de gzip optimizada
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types 
            text/plain 
            text/css 
            text/xml 
            text/javascript 
            application/x-javascript 
            application/xml+rss 
            application/javascript
            application/json
            application/xml;
        
        # Configuración específica para assets de Vite (debe ir ANTES de la regla general)
        location /build/ {
            try_files $uri =404;
            expires 1y;
            add_header Cache-Control "public, immutable";
            access_log off;
            
            # Configurar MIME types específicos para Vite
            location ~* \.css$ {
                add_header Content-Type "text/css";
            }
            
            location ~* \.js$ {
                add_header Content-Type "application/javascript";
            }
        }
        
        # Configuración de cache para assets estáticos (debe ir DESPUÉS de /build/)
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|webp)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
            access_log off;
            try_files $uri =404;
        }
        
        # Health check endpoint
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        location / {
          if ($REQUEST_METHOD = 'OPTIONS') {
            # add CORS headers
            add_header 'Access-Control-Allow-Origin' '$http_origin';
            add_header 'Access-Control-Allow-Methods' 'POST, GET, DELETE, PUT, PATCH, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Origin, Authorization, Accept, Content-Type, X-Request-With, X-XSRF-TOKEN';
            add_header 'Access-Control-Allow-Credentials' 'true';

            # Make this preflight request valid for 20 days
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
          }
        # Configuración principal de Laravel (debe ir AL FINAL)
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }
        
        # Configuración de PHP-FPM optimizada
        location ~ \.php$ {
            fastcgi_pass php-fpm;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            
            # Configuración de timeout
            fastcgi_read_timeout 300;
            fastcgi_connect_timeout 300;
            fastcgi_send_timeout 300;
            
            # Configuración de buffer optimizada
            fastcgi_buffer_size 128k;
            fastcgi_buffers 4 256k;
            fastcgi_busy_buffers_size 256k;
            fastcgi_temp_file_write_size 256k;
            
            # Configuración de cache
            fastcgi_cache_valid 200 60m;
            fastcgi_cache_use_stale error timeout updating invalid_header http_500;
        }
        
        # Denegar acceso a archivos sensibles
        location ~ /\. {
            deny all;
        }
        
        location ~ /\.ht {
            deny all;
        }
        
        location ~ /\.env {
            deny all;
        }
        
        location ~ /\.git {
            deny all;
        }
        
        location ~ /composer\.(json|lock)$ {
            deny all;
        }
        
        location ~ /package(-lock)?\.json$ {
            deny all;
        }
        
        # Configuración de error pages
        error_page 404 /index.php;
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
