apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: portafolio
  annotations:
  ignore-check.kube-linter.io/privileged-container: "This deployment needs to run as privileged because it needs kernel access"
  ignore-check.kube-linter.io/no-read-only-root-fs: "This deployment needs to run with a writable root filesystem to allow Nginx to write logs and cache files"
  ignore-check.kube-linter.io/no-run-as-non-root: "This deployment needs to run as root to allow Nginx to bind to port 80"
  ignore-check.kube-linter.io/no-run-as-user: "This deployment needs to run as root to allow Nginx to bind to port 80"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: php-fpm
          image: migbertweb/portafolio-app
          securityContext:
            runAsNonRoot: false
            runAsUser: 101
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: laravel-config-env
            - secretRef:
                name: laravel-secret-env
          volumeMounts:
            - name: laravel-code
              mountPath: /var/www/html
            - name: laravel-storage
              mountPath: /var/www/html/storage
            - name: laravel-cache
              mountPath: /var/www/html/bootstrap/cache
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: laravel-code
          persistentVolumeClaim:
            claimName: laravel-pvc
        - name: laravel-storage
          emptyDir: {}
        - name: laravel-cache
          emptyDir: {}
