apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: portafolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: php-fpm
          image: migbertweb/portafolio-app
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          initContainers:
            - name: fix-permissions
              image: busybox
              command: ["sh", "-c", "chown -R 1000:1000 /storage /cache"]
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: laravel-config-env
            - secretRef:
                name: laravel-secret-env
          volumeMounts:
            - name: laravel-code
              mountPath: /var/www/html
            - name: laravel-storage
              mountPath: /var/www/html/storage
            - name: laravel-cache
              mountPath: /var/www/html/bootstrap/cache
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: laravel-code
          persistentVolumeClaim:
            claimName: laravel-pvc
        - name: laravel-storage
          emptyDir: {}
        - name: laravel-cache
          emptyDir: {}
