name: CI/CD Portafolio App
description: Deploy de la aplicación Portafolio a Kubernetes con validaciones y notificaciones

on:
  push:
    branches:
      - dev

jobs:
  build:
    ### Evita que el job corra si fue ejecutado por el bot
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      ######### Instalacion de herramientas necesarias para K8s ##########
      - name: Setup arkade e instalar las herramientas
        uses: alexellis/arkade-get@master
        with:
          sops: latest
      # Instalacion de ksops
      - name: Instalar KSOPS
        run: |
          mkdir -p ~/.config/kustomize/plugin/viaduct.ai/v1/ksops
          curl -LO https://github.com/viaduct-ai/kustomize-sops/releases/download/v4.3.3/ksops_4.3.3_Linux_x86_64.tar.gz
          tar -xzf ksops_4.3.3_Linux_x86_64.tar.gz
          rm ksops_4.3.3_Linux_x86_64.tar.gz
          mv ksops ~/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
      # Instalar Age y configurar clave
      - name: Instalar Age
        run: |
          curl -L https://github.com/FiloSottile/age/releases/download/v1.2.1/age-v1.2.1-linux-amd64.tar.gz | tar xz
          sudo mv age/age /usr/local/bin/
          sudo mv age/age-keygen /usr/local/bin/
      # Configurar clave privada de Age
      - name: Configurar clave privada de Age
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.SOPS_AGE_KEY }}" > ~/.config/sops/age/keys.txt

      - name: check las herramientas
        run: |
          echo "kubectl:" && kubectl version --client
          echo "sops:" && sops --version
          echo "age:" && age --version

      ######### checkout el repo ##########
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      # Configurar Git
      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      ####
      # Detectar cambios en carpeta app/
      - name: Detectar cambios en carpeta app/
        id: check_app
        run: |
          git fetch --depth=2 origin ${{ github.ref }}
          if git diff --quiet HEAD^ HEAD -- ${{ github.workspace }}/apps/portafolio/app; then
            echo "Sin cambios en carpeta app/"
            echo "app_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Cambios detectados en carpeta app/"
            echo "app_changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Construir manifiestos con Kustomize
        run: |
          set -euo pipefail
          echo "📦 Construyendo manifiestos con Kustomize..."
          kustomize build --enable-alpha-plugins --enable-exec k8s/overlays/prod > kustomize-output.yaml

      - name: Subir manifiestos generados como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: kustomize-manifests
          path: kustomize-output.yaml

      # Generacion de nuevo tag semántico
      - name: Generar nuevo tag semántico
        id: tag
        if: steps.check_app.outputs.app_changed == 'true'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_PAT }}
          release_branches: master
          tag_prefix: "v"
          default_bump: patch

  lint:
    needs: build
    uses: migbertweb/ghaction-k8s-linter/.github/workflows/lint-k8s.yml@master
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
